// Automatically generated by MockGen. DO NOT EDIT!
// Source: marathon/address_resolver.go

package marathon

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of AddressResolver interface
type MockAddressResolver struct {
	ctrl     *gomock.Controller
	recorder *_MockAddressResolverRecorder
}

// Recorder for MockAddressResolver (not exported)
type _MockAddressResolverRecorder struct {
	mock *MockAddressResolver
}

func NewMockAddressResolver(ctrl *gomock.Controller) *MockAddressResolver {
	mock := &MockAddressResolver{ctrl: ctrl}
	mock.recorder = &_MockAddressResolverRecorder{mock}
	return mock
}

func (_m *MockAddressResolver) EXPECT() *_MockAddressResolverRecorder {
	return _m.recorder
}

func (_m *MockAddressResolver) Resolve(hostname string) (string, error) {
	ret := _m.ctrl.Call(_m, "Resolve", hostname)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAddressResolverRecorder) Resolve(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Resolve", arg0)
}
